version: '3.3'
services:   
    web:
        build:
           context: .
           dockerfile: Dockerfile
        hostname: commicado-ui-client   
        ports:
            - "80:3000"   
        
